### ISSUE TITLE
Add error checking for failed commands

### ISSUE THREAD

**Issue by Rldeckard** [Rldeckard/sshRunCMD#7]
like ansible fail/pass on "^".

**Comment by Rldeckard** [comment]
Major quality of life issue, but script needs to be done first before adding a "new version" basically

**Comment by Rldeckard** [comment]
Grabbed issue

**Comment by infosecwatchman** [comment]
Failed commands are not currently tracked for end-of-program status report. Reopening for visibility.

**Comment by infosecwatchman** [comment]
Added with #25
